// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateRequest struct {
	RawIdToken           string   `protobuf:"bytes,1,opt,name=raw_id_token,json=rawIdToken,proto3" json:"raw_id_token,omitempty"`
	ClaimNames           []string `protobuf:"bytes,2,rep,name=claim_names,json=claimNames,proto3" json:"claim_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetRawIdToken() string {
	if m != nil {
		return m.RawIdToken
	}
	return ""
}

func (m *ValidateRequest) GetClaimNames() []string {
	if m != nil {
		return m.ClaimNames
	}
	return nil
}

type ValidateResponse struct {
	Claims               map[string]*any.Any `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetClaims() map[string]*any.Any {
	if m != nil {
		return m.Claims
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidateRequest)(nil), "auth.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "auth.ValidateResponse")
	proto.RegisterMapType((map[string]*any.Any)(nil), "auth.ValidateResponse.ClaimsEntry")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x49, 0xab, 0x65, 0xbe, 0x0a, 0x8e, 0xa0, 0x52, 0x7b, 0xb1, 0xf4, 0x54, 0x3c, 0x64,
	0x50, 0x2f, 0x3a, 0x4f, 0x53, 0x04, 0xbd, 0x28, 0xd4, 0xe1, 0xc1, 0x4b, 0xc9, 0xd6, 0xe7, 0x56,
	0xd6, 0x25, 0xb3, 0x4d, 0x36, 0xfa, 0x6b, 0xfc, 0xab, 0x92, 0x74, 0x43, 0x19, 0xde, 0x1e, 0x5f,
	0xbf, 0x26, 0xdf, 0x0b, 0x00, 0xd7, 0x6a, 0xce, 0x56, 0xb5, 0x54, 0x92, 0x1e, 0x98, 0x39, 0xbc,
	0x98, 0x49, 0x39, 0xab, 0x70, 0x60, 0xd9, 0x44, 0x7f, 0x0e, 0xb8, 0x68, 0x3b, 0x21, 0x1e, 0xc3,
	0xc9, 0x3b, 0xaf, 0xca, 0x82, 0x2b, 0xcc, 0xf0, 0x4b, 0x63, 0xa3, 0x68, 0x04, 0xc7, 0x35, 0xdf,
	0xe4, 0x65, 0x91, 0x2b, 0xb9, 0x40, 0x11, 0x90, 0x88, 0x24, 0x47, 0x19, 0xd4, 0x7c, 0xf3, 0x5c,
	0x8c, 0x0d, 0xa1, 0x97, 0xe0, 0x4f, 0x2b, 0x5e, 0x2e, 0x73, 0xc1, 0x97, 0xd8, 0x04, 0x4e, 0xe4,
	0x1a, 0xc1, 0xa2, 0x17, 0x43, 0xe2, 0x6f, 0x02, 0xfd, 0xdf, 0x63, 0x9b, 0x95, 0x14, 0x0d, 0xd2,
	0x21, 0x78, 0x56, 0x69, 0x02, 0x12, 0xb9, 0x89, 0x9f, 0xc6, 0xcc, 0x86, 0xee, 0x7b, 0xec, 0xc1,
	0x4a, 0x8f, 0x42, 0xd5, 0x6d, 0xb6, 0xfd, 0x23, 0x7c, 0x05, 0xff, 0x0f, 0xa6, 0x7d, 0x70, 0x17,
	0xd8, 0x6e, 0xcb, 0xcc, 0x48, 0xaf, 0xe0, 0x70, 0xcd, 0x2b, 0x8d, 0x81, 0x13, 0x91, 0xc4, 0x4f,
	0x4f, 0x59, 0xb7, 0x32, 0xdb, 0xad, 0xcc, 0x46, 0xa2, 0xcd, 0x3a, 0x65, 0xe8, 0xdc, 0x90, 0xf4,
	0x09, 0xfc, 0x91, 0x56, 0xf3, 0x37, 0xac, 0xd7, 0xe5, 0x14, 0xe9, 0x2d, 0xf4, 0x76, 0x1d, 0xf4,
	0x6c, 0xbf, 0xcb, 0x3e, 0x4b, 0x78, 0xfe, 0x7f, 0xee, 0x7d, 0xef, 0xc3, 0x63, 0x77, 0xe6, 0xd3,
	0xc4, 0xb3, 0x97, 0x5d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x20, 0x8b, 0x7f, 0x81, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
