// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fight.proto

package fight

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hero_Gender int32

const (
	Hero_MALE   Hero_Gender = 0
	Hero_FEMALE Hero_Gender = 1
)

var Hero_Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}

var Hero_Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Hero_Gender) String() string {
	return proto.EnumName(Hero_Gender_name, int32(x))
}

func (Hero_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{4, 0}
}

type ListBossesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBossesRequest) Reset()         { *m = ListBossesRequest{} }
func (m *ListBossesRequest) String() string { return proto.CompactTextString(m) }
func (*ListBossesRequest) ProtoMessage()    {}
func (*ListBossesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{0}
}

func (m *ListBossesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBossesRequest.Unmarshal(m, b)
}
func (m *ListBossesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBossesRequest.Marshal(b, m, deterministic)
}
func (m *ListBossesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBossesRequest.Merge(m, src)
}
func (m *ListBossesRequest) XXX_Size() int {
	return xxx_messageInfo_ListBossesRequest.Size(m)
}
func (m *ListBossesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBossesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBossesRequest proto.InternalMessageInfo

type FightRequest struct {
	// Types that are valid to be assigned to Action:
	//	*FightRequest_Archive_
	//	*FightRequest_Start_
	//	*FightRequest_Fight_
	Action               isFightRequest_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FightRequest) Reset()         { *m = FightRequest{} }
func (m *FightRequest) String() string { return proto.CompactTextString(m) }
func (*FightRequest) ProtoMessage()    {}
func (*FightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{1}
}

func (m *FightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightRequest.Unmarshal(m, b)
}
func (m *FightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightRequest.Marshal(b, m, deterministic)
}
func (m *FightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightRequest.Merge(m, src)
}
func (m *FightRequest) XXX_Size() int {
	return xxx_messageInfo_FightRequest.Size(m)
}
func (m *FightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FightRequest proto.InternalMessageInfo

type isFightRequest_Action interface {
	isFightRequest_Action()
}

type FightRequest_Archive_ struct {
	Archive *FightRequest_Archive `protobuf:"bytes,1,opt,name=archive,proto3,oneof"`
}

type FightRequest_Start_ struct {
	Start *FightRequest_Start `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type FightRequest_Fight_ struct {
	Fight *FightRequest_Fight `protobuf:"bytes,3,opt,name=fight,proto3,oneof"`
}

func (*FightRequest_Archive_) isFightRequest_Action() {}

func (*FightRequest_Start_) isFightRequest_Action() {}

func (*FightRequest_Fight_) isFightRequest_Action() {}

func (m *FightRequest) GetAction() isFightRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *FightRequest) GetArchive() *FightRequest_Archive {
	if x, ok := m.GetAction().(*FightRequest_Archive_); ok {
		return x.Archive
	}
	return nil
}

func (m *FightRequest) GetStart() *FightRequest_Start {
	if x, ok := m.GetAction().(*FightRequest_Start_); ok {
		return x.Start
	}
	return nil
}

func (m *FightRequest) GetFight() *FightRequest_Fight {
	if x, ok := m.GetAction().(*FightRequest_Fight_); ok {
		return x.Fight
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FightRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FightRequest_Archive_)(nil),
		(*FightRequest_Start_)(nil),
		(*FightRequest_Fight_)(nil),
	}
}

type FightRequest_Archive struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightRequest_Archive) Reset()         { *m = FightRequest_Archive{} }
func (m *FightRequest_Archive) String() string { return proto.CompactTextString(m) }
func (*FightRequest_Archive) ProtoMessage()    {}
func (*FightRequest_Archive) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{1, 0}
}

func (m *FightRequest_Archive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightRequest_Archive.Unmarshal(m, b)
}
func (m *FightRequest_Archive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightRequest_Archive.Marshal(b, m, deterministic)
}
func (m *FightRequest_Archive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightRequest_Archive.Merge(m, src)
}
func (m *FightRequest_Archive) XXX_Size() int {
	return xxx_messageInfo_FightRequest_Archive.Size(m)
}
func (m *FightRequest_Archive) XXX_DiscardUnknown() {
	xxx_messageInfo_FightRequest_Archive.DiscardUnknown(m)
}

var xxx_messageInfo_FightRequest_Archive proto.InternalMessageInfo

type FightRequest_Start struct {
	Hero                 *Hero    `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	Boss                 *Boss    `protobuf:"bytes,2,opt,name=boss,proto3" json:"boss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightRequest_Start) Reset()         { *m = FightRequest_Start{} }
func (m *FightRequest_Start) String() string { return proto.CompactTextString(m) }
func (*FightRequest_Start) ProtoMessage()    {}
func (*FightRequest_Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{1, 1}
}

func (m *FightRequest_Start) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightRequest_Start.Unmarshal(m, b)
}
func (m *FightRequest_Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightRequest_Start.Marshal(b, m, deterministic)
}
func (m *FightRequest_Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightRequest_Start.Merge(m, src)
}
func (m *FightRequest_Start) XXX_Size() int {
	return xxx_messageInfo_FightRequest_Start.Size(m)
}
func (m *FightRequest_Start) XXX_DiscardUnknown() {
	xxx_messageInfo_FightRequest_Start.DiscardUnknown(m)
}

var xxx_messageInfo_FightRequest_Start proto.InternalMessageInfo

func (m *FightRequest_Start) GetHero() *Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

func (m *FightRequest_Start) GetBoss() *Boss {
	if m != nil {
		return m.Boss
	}
	return nil
}

type FightRequest_Fight struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightRequest_Fight) Reset()         { *m = FightRequest_Fight{} }
func (m *FightRequest_Fight) String() string { return proto.CompactTextString(m) }
func (*FightRequest_Fight) ProtoMessage()    {}
func (*FightRequest_Fight) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{1, 2}
}

func (m *FightRequest_Fight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightRequest_Fight.Unmarshal(m, b)
}
func (m *FightRequest_Fight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightRequest_Fight.Marshal(b, m, deterministic)
}
func (m *FightRequest_Fight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightRequest_Fight.Merge(m, src)
}
func (m *FightRequest_Fight) XXX_Size() int {
	return xxx_messageInfo_FightRequest_Fight.Size(m)
}
func (m *FightRequest_Fight) XXX_DiscardUnknown() {
	xxx_messageInfo_FightRequest_Fight.DiscardUnknown(m)
}

var xxx_messageInfo_FightRequest_Fight proto.InternalMessageInfo

type FightResponse struct {
	// Types that are valid to be assigned to Action:
	//	*FightResponse_Fail_
	//	*FightResponse_Success_
	//	*FightResponse_CurrentStatus_
	Action               isFightResponse_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FightResponse) Reset()         { *m = FightResponse{} }
func (m *FightResponse) String() string { return proto.CompactTextString(m) }
func (*FightResponse) ProtoMessage()    {}
func (*FightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{2}
}

func (m *FightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightResponse.Unmarshal(m, b)
}
func (m *FightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightResponse.Marshal(b, m, deterministic)
}
func (m *FightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightResponse.Merge(m, src)
}
func (m *FightResponse) XXX_Size() int {
	return xxx_messageInfo_FightResponse.Size(m)
}
func (m *FightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FightResponse proto.InternalMessageInfo

type isFightResponse_Action interface {
	isFightResponse_Action()
}

type FightResponse_Fail_ struct {
	Fail *FightResponse_Fail `protobuf:"bytes,1,opt,name=fail,proto3,oneof"`
}

type FightResponse_Success_ struct {
	Success *FightResponse_Success `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type FightResponse_CurrentStatus_ struct {
	CurrentStatus *FightResponse_CurrentStatus `protobuf:"bytes,3,opt,name=current_status,json=currentStatus,proto3,oneof"`
}

func (*FightResponse_Fail_) isFightResponse_Action() {}

func (*FightResponse_Success_) isFightResponse_Action() {}

func (*FightResponse_CurrentStatus_) isFightResponse_Action() {}

func (m *FightResponse) GetAction() isFightResponse_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *FightResponse) GetFail() *FightResponse_Fail {
	if x, ok := m.GetAction().(*FightResponse_Fail_); ok {
		return x.Fail
	}
	return nil
}

func (m *FightResponse) GetSuccess() *FightResponse_Success {
	if x, ok := m.GetAction().(*FightResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *FightResponse) GetCurrentStatus() *FightResponse_CurrentStatus {
	if x, ok := m.GetAction().(*FightResponse_CurrentStatus_); ok {
		return x.CurrentStatus
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FightResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FightResponse_Fail_)(nil),
		(*FightResponse_Success_)(nil),
		(*FightResponse_CurrentStatus_)(nil),
	}
}

type FightResponse_Fail struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightResponse_Fail) Reset()         { *m = FightResponse_Fail{} }
func (m *FightResponse_Fail) String() string { return proto.CompactTextString(m) }
func (*FightResponse_Fail) ProtoMessage()    {}
func (*FightResponse_Fail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{2, 0}
}

func (m *FightResponse_Fail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightResponse_Fail.Unmarshal(m, b)
}
func (m *FightResponse_Fail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightResponse_Fail.Marshal(b, m, deterministic)
}
func (m *FightResponse_Fail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightResponse_Fail.Merge(m, src)
}
func (m *FightResponse_Fail) XXX_Size() int {
	return xxx_messageInfo_FightResponse_Fail.Size(m)
}
func (m *FightResponse_Fail) XXX_DiscardUnknown() {
	xxx_messageInfo_FightResponse_Fail.DiscardUnknown(m)
}

var xxx_messageInfo_FightResponse_Fail proto.InternalMessageInfo

type FightResponse_Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightResponse_Success) Reset()         { *m = FightResponse_Success{} }
func (m *FightResponse_Success) String() string { return proto.CompactTextString(m) }
func (*FightResponse_Success) ProtoMessage()    {}
func (*FightResponse_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{2, 1}
}

func (m *FightResponse_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightResponse_Success.Unmarshal(m, b)
}
func (m *FightResponse_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightResponse_Success.Marshal(b, m, deterministic)
}
func (m *FightResponse_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightResponse_Success.Merge(m, src)
}
func (m *FightResponse_Success) XXX_Size() int {
	return xxx_messageInfo_FightResponse_Success.Size(m)
}
func (m *FightResponse_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_FightResponse_Success.DiscardUnknown(m)
}

var xxx_messageInfo_FightResponse_Success proto.InternalMessageInfo

type FightResponse_CurrentStatus struct {
	HeroHp               uint32   `protobuf:"varint,1,opt,name=hero_hp,json=heroHp,proto3" json:"hero_hp,omitempty"`
	BossHp               uint32   `protobuf:"varint,2,opt,name=boss_hp,json=bossHp,proto3" json:"boss_hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightResponse_CurrentStatus) Reset()         { *m = FightResponse_CurrentStatus{} }
func (m *FightResponse_CurrentStatus) String() string { return proto.CompactTextString(m) }
func (*FightResponse_CurrentStatus) ProtoMessage()    {}
func (*FightResponse_CurrentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{2, 2}
}

func (m *FightResponse_CurrentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightResponse_CurrentStatus.Unmarshal(m, b)
}
func (m *FightResponse_CurrentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightResponse_CurrentStatus.Marshal(b, m, deterministic)
}
func (m *FightResponse_CurrentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightResponse_CurrentStatus.Merge(m, src)
}
func (m *FightResponse_CurrentStatus) XXX_Size() int {
	return xxx_messageInfo_FightResponse_CurrentStatus.Size(m)
}
func (m *FightResponse_CurrentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FightResponse_CurrentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FightResponse_CurrentStatus proto.InternalMessageInfo

func (m *FightResponse_CurrentStatus) GetHeroHp() uint32 {
	if m != nil {
		return m.HeroHp
	}
	return 0
}

func (m *FightResponse_CurrentStatus) GetBossHp() uint32 {
	if m != nil {
		return m.BossHp
	}
	return 0
}

type ListHerosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHerosRequest) Reset()         { *m = ListHerosRequest{} }
func (m *ListHerosRequest) String() string { return proto.CompactTextString(m) }
func (*ListHerosRequest) ProtoMessage()    {}
func (*ListHerosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{3}
}

func (m *ListHerosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHerosRequest.Unmarshal(m, b)
}
func (m *ListHerosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHerosRequest.Marshal(b, m, deterministic)
}
func (m *ListHerosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHerosRequest.Merge(m, src)
}
func (m *ListHerosRequest) XXX_Size() int {
	return xxx_messageInfo_ListHerosRequest.Size(m)
}
func (m *ListHerosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHerosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHerosRequest proto.InternalMessageInfo

type Hero struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender               Hero_Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=fight.Hero_Gender" json:"gender,omitempty"`
	Hp                   uint32      `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	AttackPower          int32       `protobuf:"varint,5,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	DefensePower         int32       `protobuf:"varint,6,opt,name=defense_power,json=defensePower,proto3" json:"defense_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{4}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hero) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Hero) GetGender() Hero_Gender {
	if m != nil {
		return m.Gender
	}
	return Hero_MALE
}

func (m *Hero) GetHp() uint32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Hero) GetAttackPower() int32 {
	if m != nil {
		return m.AttackPower
	}
	return 0
}

func (m *Hero) GetDefensePower() int32 {
	if m != nil {
		return m.DefensePower
	}
	return 0
}

type Boss struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttackPower          int32    `protobuf:"varint,2,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	DefensePower         int32    `protobuf:"varint,3,opt,name=defense_power,json=defensePower,proto3" json:"defense_power,omitempty"`
	Hp                   uint32   `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	Level                uint32   `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boss) Reset()         { *m = Boss{} }
func (m *Boss) String() string { return proto.CompactTextString(m) }
func (*Boss) ProtoMessage()    {}
func (*Boss) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{5}
}

func (m *Boss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boss.Unmarshal(m, b)
}
func (m *Boss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boss.Marshal(b, m, deterministic)
}
func (m *Boss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boss.Merge(m, src)
}
func (m *Boss) XXX_Size() int {
	return xxx_messageInfo_Boss.Size(m)
}
func (m *Boss) XXX_DiscardUnknown() {
	xxx_messageInfo_Boss.DiscardUnknown(m)
}

var xxx_messageInfo_Boss proto.InternalMessageInfo

func (m *Boss) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Boss) GetAttackPower() int32 {
	if m != nil {
		return m.AttackPower
	}
	return 0
}

func (m *Boss) GetDefensePower() int32 {
	if m != nil {
		return m.DefensePower
	}
	return 0
}

func (m *Boss) GetHp() uint32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Boss) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type SelectHeroRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectHeroRequest) Reset()         { *m = SelectHeroRequest{} }
func (m *SelectHeroRequest) String() string { return proto.CompactTextString(m) }
func (*SelectHeroRequest) ProtoMessage()    {}
func (*SelectHeroRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{6}
}

func (m *SelectHeroRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectHeroRequest.Unmarshal(m, b)
}
func (m *SelectHeroRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectHeroRequest.Marshal(b, m, deterministic)
}
func (m *SelectHeroRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectHeroRequest.Merge(m, src)
}
func (m *SelectHeroRequest) XXX_Size() int {
	return xxx_messageInfo_SelectHeroRequest.Size(m)
}
func (m *SelectHeroRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectHeroRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectHeroRequest proto.InternalMessageInfo

func (m *SelectHeroRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SelectHeroResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectHeroResponse) Reset()         { *m = SelectHeroResponse{} }
func (m *SelectHeroResponse) String() string { return proto.CompactTextString(m) }
func (*SelectHeroResponse) ProtoMessage()    {}
func (*SelectHeroResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a9b36907fd4a279, []int{7}
}

func (m *SelectHeroResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectHeroResponse.Unmarshal(m, b)
}
func (m *SelectHeroResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectHeroResponse.Marshal(b, m, deterministic)
}
func (m *SelectHeroResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectHeroResponse.Merge(m, src)
}
func (m *SelectHeroResponse) XXX_Size() int {
	return xxx_messageInfo_SelectHeroResponse.Size(m)
}
func (m *SelectHeroResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectHeroResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectHeroResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("fight.Hero_Gender", Hero_Gender_name, Hero_Gender_value)
	proto.RegisterType((*ListBossesRequest)(nil), "fight.ListBossesRequest")
	proto.RegisterType((*FightRequest)(nil), "fight.FightRequest")
	proto.RegisterType((*FightRequest_Archive)(nil), "fight.FightRequest.Archive")
	proto.RegisterType((*FightRequest_Start)(nil), "fight.FightRequest.Start")
	proto.RegisterType((*FightRequest_Fight)(nil), "fight.FightRequest.Fight")
	proto.RegisterType((*FightResponse)(nil), "fight.FightResponse")
	proto.RegisterType((*FightResponse_Fail)(nil), "fight.FightResponse.Fail")
	proto.RegisterType((*FightResponse_Success)(nil), "fight.FightResponse.Success")
	proto.RegisterType((*FightResponse_CurrentStatus)(nil), "fight.FightResponse.CurrentStatus")
	proto.RegisterType((*ListHerosRequest)(nil), "fight.ListHerosRequest")
	proto.RegisterType((*Hero)(nil), "fight.Hero")
	proto.RegisterType((*Boss)(nil), "fight.Boss")
	proto.RegisterType((*SelectHeroRequest)(nil), "fight.SelectHeroRequest")
	proto.RegisterType((*SelectHeroResponse)(nil), "fight.SelectHeroResponse")
}

func init() { proto.RegisterFile("fight.proto", fileDescriptor_0a9b36907fd4a279) }

var fileDescriptor_0a9b36907fd4a279 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x5d, 0xff, 0x34, 0x93, 0xba, 0x6a, 0xa7, 0x95, 0xea, 0xfa, 0xfb, 0x04, 0xc5, 0x5c,
	0x10, 0x71, 0x61, 0x4a, 0x0a, 0x02, 0x89, 0xab, 0x04, 0x35, 0x18, 0x51, 0x24, 0xb4, 0xb9, 0xe3,
	0x26, 0x72, 0xdd, 0x4d, 0x6c, 0x11, 0x6c, 0xe3, 0xdd, 0x94, 0x57, 0xe0, 0x09, 0x78, 0x05, 0x5e,
	0x87, 0x07, 0xe1, 0x21, 0xd0, 0xfe, 0x24, 0x35, 0x89, 0x91, 0xb8, 0xdb, 0x9d, 0x73, 0x66, 0xe6,
	0xec, 0xd9, 0xd9, 0x85, 0xde, 0x2c, 0x9f, 0x67, 0x3c, 0xaa, 0xea, 0x92, 0x97, 0x68, 0xcb, 0x4d,
	0x78, 0x04, 0x87, 0x57, 0x39, 0xe3, 0xa3, 0x92, 0x31, 0xca, 0x08, 0xfd, 0xb2, 0xa4, 0x8c, 0x87,
	0xdf, 0x4d, 0xd8, 0x1b, 0x0b, 0x58, 0x07, 0xf0, 0x05, 0xb8, 0x49, 0x9d, 0x66, 0xf9, 0x2d, 0xf5,
	0x8d, 0x33, 0xa3, 0xdf, 0x1b, 0xfc, 0x17, 0xa9, 0x5a, 0x4d, 0x56, 0x34, 0x54, 0x94, 0xb8, 0x43,
	0x56, 0x6c, 0x7c, 0x0a, 0x36, 0xe3, 0x49, 0xcd, 0x7d, 0x53, 0xa6, 0x9d, 0xb6, 0xa5, 0x4d, 0x04,
	0x21, 0xee, 0x10, 0xc5, 0x14, 0x29, 0x92, 0xe4, 0xef, 0xfc, 0x3d, 0x45, 0x6e, 0x44, 0x8a, 0xc4,
	0x82, 0x2e, 0xb8, 0xba, 0x77, 0xf0, 0x16, 0x6c, 0x59, 0x0f, 0xef, 0x83, 0x95, 0xd1, 0xba, 0xd4,
	0x7a, 0x7b, 0xba, 0x4a, 0x4c, 0xeb, 0x92, 0x48, 0x40, 0x10, 0xae, 0x4b, 0xc6, 0xb4, 0xb2, 0x15,
	0x41, 0x18, 0x41, 0x24, 0x10, 0xb8, 0x60, 0xcb, 0x3e, 0xa3, 0x5d, 0x70, 0x92, 0x94, 0xe7, 0x65,
	0x11, 0xfe, 0x30, 0xc1, 0xd3, 0x42, 0x58, 0x55, 0x16, 0x8c, 0xe2, 0x13, 0xb0, 0x66, 0x49, 0xbe,
	0xd0, 0x6d, 0x36, 0xc4, 0x2a, 0x4e, 0x34, 0x4e, 0xf2, 0x45, 0xdc, 0x21, 0x92, 0x88, 0x2f, 0xc1,
	0x65, 0xcb, 0x34, 0xa5, 0xeb, 0xce, 0xff, 0xb7, 0xe6, 0x4c, 0x14, 0x47, 0x78, 0xa9, 0xe9, 0xf8,
	0x0e, 0xf6, 0xd3, 0x65, 0x5d, 0xd3, 0x82, 0x4f, 0x19, 0x4f, 0xf8, 0x92, 0x69, 0x87, 0xc2, 0xd6,
	0x02, 0xaf, 0x15, 0x75, 0x22, 0x99, 0x71, 0x87, 0x78, 0x69, 0x33, 0x10, 0x38, 0x60, 0x09, 0x59,
	0xc2, 0x3a, 0xdd, 0x2a, 0x18, 0x82, 0xf7, 0x47, 0x12, 0x9e, 0x80, 0x2b, 0x9c, 0x9a, 0x66, 0x95,
	0x3c, 0x9e, 0x47, 0x1c, 0xb1, 0x8d, 0x2b, 0x01, 0x08, 0x87, 0x04, 0x60, 0x2a, 0x40, 0x6c, 0xe3,
	0xaa, 0xe1, 0x14, 0xc2, 0x81, 0x98, 0x2b, 0xe1, 0xf7, 0x7a, 0xac, 0x7e, 0x1a, 0x60, 0x89, 0x00,
	0x22, 0x58, 0x45, 0xf2, 0x59, 0xcd, 0x52, 0x97, 0xc8, 0x35, 0x1e, 0xc0, 0x4e, 0x32, 0xa7, 0xba,
	0x9e, 0x58, 0xe2, 0x63, 0x70, 0xe6, 0xb4, 0xb8, 0xa1, 0xb5, 0x3c, 0xe7, 0xfe, 0x00, 0x1b, 0x77,
	0x18, 0xbd, 0x91, 0x08, 0xd1, 0x0c, 0xdc, 0x07, 0x33, 0xab, 0x7c, 0x4b, 0x26, 0x9b, 0x59, 0x85,
	0x0f, 0x60, 0x2f, 0xe1, 0x3c, 0x49, 0x3f, 0x4d, 0xab, 0xf2, 0x2b, 0xad, 0x7d, 0xfb, 0xcc, 0xe8,
	0xdb, 0xa4, 0xa7, 0x62, 0x1f, 0x44, 0x08, 0x1f, 0x82, 0x77, 0x43, 0x67, 0xb4, 0x60, 0x54, 0x73,
	0x1c, 0xc9, 0xd9, 0xd3, 0x41, 0x49, 0x0a, 0xef, 0x81, 0xa3, 0x3a, 0xe1, 0x2e, 0x58, 0xef, 0x87,
	0x57, 0x97, 0x07, 0x1d, 0x04, 0x70, 0xc6, 0x97, 0x72, 0x6d, 0x84, 0xdf, 0x0c, 0xb0, 0xc4, 0xc8,
	0xb4, 0x1e, 0x69, 0x53, 0x84, 0xf9, 0x0f, 0x22, 0x76, 0xb6, 0x45, 0x6c, 0x1d, 0xee, 0x18, 0xec,
	0x05, 0xbd, 0xa5, 0x0b, 0x79, 0x2a, 0x8f, 0xa8, 0x4d, 0xf8, 0x08, 0x0e, 0x27, 0x74, 0x41, 0x53,
	0xe9, 0xf9, 0xea, 0xe1, 0xb6, 0xc8, 0x0a, 0x8f, 0x01, 0x9b, 0x44, 0x35, 0x2f, 0x83, 0x5f, 0x86,
	0x1e, 0x77, 0xbc, 0x80, 0xee, 0xfa, 0xea, 0xf0, 0x44, 0x9b, 0xbe, 0x79, 0x99, 0x41, 0xf3, 0x45,
	0x9d, 0x1b, 0x38, 0x04, 0xb8, 0x2b, 0x8a, 0xbe, 0x06, 0xb7, 0x04, 0x05, 0xa7, 0x2d, 0x88, 0x7e,
	0x4a, 0xcf, 0x01, 0xee, 0xbe, 0xa2, 0x75, 0x89, 0xad, 0xdf, 0x29, 0x68, 0x3e, 0xd5, 0x73, 0x03,
	0x9f, 0xad, 0x74, 0x1f, 0xb5, 0xfc, 0x14, 0xc1, 0x71, 0xdb, 0xe3, 0xe8, 0x1b, 0xa3, 0xee, 0x47,
	0x37, 0x7a, 0x25, 0xa1, 0x6b, 0x47, 0x7e, 0x88, 0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0x2a, 0x90, 0x28, 0x1f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FightClient is the client API for Fight service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FightClient interface {
	ListHeros(ctx context.Context, in *ListHerosRequest, opts ...grpc.CallOption) (Fight_ListHerosClient, error)
	SelectHero(ctx context.Context, in *SelectHeroRequest, opts ...grpc.CallOption) (*SelectHeroResponse, error)
	ListBosses(ctx context.Context, in *ListBossesRequest, opts ...grpc.CallOption) (Fight_ListBossesClient, error)
	Fight(ctx context.Context, opts ...grpc.CallOption) (Fight_FightClient, error)
}

type fightClient struct {
	cc *grpc.ClientConn
}

func NewFightClient(cc *grpc.ClientConn) FightClient {
	return &fightClient{cc}
}

func (c *fightClient) ListHeros(ctx context.Context, in *ListHerosRequest, opts ...grpc.CallOption) (Fight_ListHerosClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fight_serviceDesc.Streams[0], "/fight.Fight/ListHeros", opts...)
	if err != nil {
		return nil, err
	}
	x := &fightListHerosClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fight_ListHerosClient interface {
	Recv() (*Hero, error)
	grpc.ClientStream
}

type fightListHerosClient struct {
	grpc.ClientStream
}

func (x *fightListHerosClient) Recv() (*Hero, error) {
	m := new(Hero)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fightClient) SelectHero(ctx context.Context, in *SelectHeroRequest, opts ...grpc.CallOption) (*SelectHeroResponse, error) {
	out := new(SelectHeroResponse)
	err := c.cc.Invoke(ctx, "/fight.Fight/SelectHero", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fightClient) ListBosses(ctx context.Context, in *ListBossesRequest, opts ...grpc.CallOption) (Fight_ListBossesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fight_serviceDesc.Streams[1], "/fight.Fight/ListBosses", opts...)
	if err != nil {
		return nil, err
	}
	x := &fightListBossesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fight_ListBossesClient interface {
	Recv() (*Boss, error)
	grpc.ClientStream
}

type fightListBossesClient struct {
	grpc.ClientStream
}

func (x *fightListBossesClient) Recv() (*Boss, error) {
	m := new(Boss)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fightClient) Fight(ctx context.Context, opts ...grpc.CallOption) (Fight_FightClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fight_serviceDesc.Streams[2], "/fight.Fight/Fight", opts...)
	if err != nil {
		return nil, err
	}
	x := &fightFightClient{stream}
	return x, nil
}

type Fight_FightClient interface {
	Send(*FightRequest) error
	CloseAndRecv() (*FightResponse, error)
	grpc.ClientStream
}

type fightFightClient struct {
	grpc.ClientStream
}

func (x *fightFightClient) Send(m *FightRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fightFightClient) CloseAndRecv() (*FightResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FightResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FightServer is the server API for Fight service.
type FightServer interface {
	ListHeros(*ListHerosRequest, Fight_ListHerosServer) error
	SelectHero(context.Context, *SelectHeroRequest) (*SelectHeroResponse, error)
	ListBosses(*ListBossesRequest, Fight_ListBossesServer) error
	Fight(Fight_FightServer) error
}

// UnimplementedFightServer can be embedded to have forward compatible implementations.
type UnimplementedFightServer struct {
}

func (*UnimplementedFightServer) ListHeros(req *ListHerosRequest, srv Fight_ListHerosServer) error {
	return status.Errorf(codes.Unimplemented, "method ListHeros not implemented")
}
func (*UnimplementedFightServer) SelectHero(ctx context.Context, req *SelectHeroRequest) (*SelectHeroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectHero not implemented")
}
func (*UnimplementedFightServer) ListBosses(req *ListBossesRequest, srv Fight_ListBossesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBosses not implemented")
}
func (*UnimplementedFightServer) Fight(srv Fight_FightServer) error {
	return status.Errorf(codes.Unimplemented, "method Fight not implemented")
}

func RegisterFightServer(s *grpc.Server, srv FightServer) {
	s.RegisterService(&_Fight_serviceDesc, srv)
}

func _Fight_ListHeros_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListHerosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FightServer).ListHeros(m, &fightListHerosServer{stream})
}

type Fight_ListHerosServer interface {
	Send(*Hero) error
	grpc.ServerStream
}

type fightListHerosServer struct {
	grpc.ServerStream
}

func (x *fightListHerosServer) Send(m *Hero) error {
	return x.ServerStream.SendMsg(m)
}

func _Fight_SelectHero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectHeroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FightServer).SelectHero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fight.Fight/SelectHero",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FightServer).SelectHero(ctx, req.(*SelectHeroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fight_ListBosses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBossesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FightServer).ListBosses(m, &fightListBossesServer{stream})
}

type Fight_ListBossesServer interface {
	Send(*Boss) error
	grpc.ServerStream
}

type fightListBossesServer struct {
	grpc.ServerStream
}

func (x *fightListBossesServer) Send(m *Boss) error {
	return x.ServerStream.SendMsg(m)
}

func _Fight_Fight_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FightServer).Fight(&fightFightServer{stream})
}

type Fight_FightServer interface {
	SendAndClose(*FightResponse) error
	Recv() (*FightRequest, error)
	grpc.ServerStream
}

type fightFightServer struct {
	grpc.ServerStream
}

func (x *fightFightServer) SendAndClose(m *FightResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fightFightServer) Recv() (*FightRequest, error) {
	m := new(FightRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Fight_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fight.Fight",
	HandlerType: (*FightServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectHero",
			Handler:    _Fight_SelectHero_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListHeros",
			Handler:       _Fight_ListHeros_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListBosses",
			Handler:       _Fight_ListBosses_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Fight",
			Handler:       _Fight_Fight_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fight.proto",
}
